workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install CocoaPods and update repo
        script: |
          flutter pub get
          cd ios
          rm -f Podfile.lock
          pod repo update
          pod install --repo-update

