// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_bAMxhKSC26amva-4qn1jSjrHL24qEcs',
    appId: '1:1013224307390:web:dfe52ceffbe43a219cbcef',
    messagingSenderId: '1013224307390',
    projectId: 'anchorage-islamabad',
    authDomain: 'anchorage-islamabad.firebaseapp.com',
    storageBucket: 'anchorage-islamabad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABWIsIY11d3G-snoR1YM1tIWUERiwQLMI',
    appId: '1:1013224307390:android:7abf2e3d28fe36489cbcef',
    messagingSenderId: '1013224307390',
    projectId: 'anchorage-islamabad',
    storageBucket: 'anchorage-islamabad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr5oe3p1-c7eScgQaikyT8wFcqLTIDryY',
    appId: '1:1013224307390:ios:c0f806f728dbb6419cbcef',
    messagingSenderId: '1013224307390',
    projectId: 'anchorage-islamabad',
    storageBucket: 'anchorage-islamabad.firebasestorage.app',
    iosBundleId: 'com.app.anchorageislamabad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr5oe3p1-c7eScgQaikyT8wFcqLTIDryY',
    appId: '1:1013224307390:ios:c0f806f728dbb6419cbcef',
    messagingSenderId: '1013224307390',
    projectId: 'anchorage-islamabad',
    storageBucket: 'anchorage-islamabad.firebasestorage.app',
    iosBundleId: 'com.app.anchorageislamabad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_bAMxhKSC26amva-4qn1jSjrHL24qEcs',
    appId: '1:1013224307390:web:ca39ad27865c301e9cbcef',
    messagingSenderId: '1013224307390',
    projectId: 'anchorage-islamabad',
    authDomain: 'anchorage-islamabad.firebaseapp.com',
    storageBucket: 'anchorage-islamabad.firebasestorage.app',
  );
}
